import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {validateHostedAdvisoryResponse} from "../src/lib/iq200/hostedEvidence.ts";
import {hostedExecutionAllowed,hostedReasoningConfig,IQ200_HOSTED_COMMISSIONING_ARMED,IQ200_PHASE7_COMMISSIONING_ARMED,IQ200_PHASE7_MODEL,phase7ScopeAllowed} from "../src/lib/iq200/hostedConfig.ts";
import {runHostedExecutionCore,type HostedExecutionControls,type HostedExecutionScope} from "../src/lib/iq200/hostedReasoningCore.ts";
import {evidenceReferenceSet,mergeRequiredSafetyWarnings,validateProviderUsage,validateReasoningResponse,REASONING_ARRAY_MAX,type ReasoningEvidence,type ReasoningResponse} from "../src/lib/iq200/reasoningCore.ts";

const source=(path:string)=>readFileSync(path,"utf8");
const forbiddenPersistenceFields=["rawResponse","rawProviderResponse","providerEnvelope","fullPrompt","systemPrompt","authorization","apiKey","OPENAI_API_KEY","bearer","secret","chainOfThought","chain_of_thought","reasoningText","internalReasoning"];
const responseKeys=["checks","confidence","evidenceUsed","hypotheses","limitations","missingInformation","observations","safetyWarnings","summary"];
const scope:HostedExecutionScope={companyId:"company-a",userId:"user-a",jobId:"job-a",sessionId:"session-a",question:"Check the fuel pressure safely"};
const evidence:ReasoningEvidence={question:scope.question,currentJob:{jobNumber:"J100",status:"OPEN",vehicle:{make:"Scania",model:"R500",type:"Truck",engineFamily:"DC13",descriptor:"REG-1 / FLEET-1"},complaint:"Low rail pressure during crank",faultCodes:["P0087"],notes:[],diagnostics:["Rail pressure 120 bar"]},relatedHistory:[{reference:"HISTORY_1",description:"Similar symptom required pressure verification",faultCodes:["P0087"],findings:["Low pressure"],repairs:["Sensor replaced after testing"],relevanceReasons:["same fault code"]}],approvedKnownFixes:[{reference:"KNOWN_FIX_1",title:"Fuel pressure verification",applicability:"DC13",faultCodes:["P0087"],diagnosticProcedure:"Measure rail pressure during crank.",expectedValues:"180-260 bar",safetyWarnings:"Wear approved eye protection.",technicalCautions:"Depressurize before service.",relevanceReasons:["same engine and code"]}],recentInteractions:[]};
const advisory=():ReasoningResponse=>({summary:"Verify the measured pressure before deciding on repair.",observations:["Rail pressure is below the supplied expected range."],hypotheses:[{title:"Fuel pressure supply fault",explanation:"The current measurement supports testing the supply circuit.",confidence:"LOW",evidenceReferences:["CURRENT_JOB","KNOWN_FIX_1"],contradictions:["History alone does not establish the current fault."],recommendedChecks:["Repeat the pressure measurement with approved equipment."]}],checks:[{description:"Repeat the rail-pressure test during crank.",purpose:"Confirm the current pressure deficit.",expectedResult:"Compare with the approved 180-260 bar range.",safetyNote:"Use eye protection and depressurize before service.",evidenceSource:"KNOWN_FIX_1"}],safetyWarnings:["Preserve the provider warning.","Wear approved eye protection."],missingInformation:["Current low-pressure supply reading."],evidenceUsed:[{category:"CURRENT_JOB",reference:"CURRENT_JOB",detail:"Current low-pressure measurement"},{category:"KNOWN_FIX",reference:"KNOWN_FIX_1",detail:"Approved pressure test"}],confidence:"LOW",limitations:["Advisory only; physical testing is required."]});

function deterministicHostedResult(){let calls=0;const transport={send:async()=>{calls++;return{response:advisory(),usage:{inputUnits:120,outputUnits:80}}}};return{calls:()=>calls,run:async()=>{const result=await transport.send(),structured=validateReasoningResponse(validateHostedAdvisoryResponse(result.response)),response=validateReasoningResponse(mergeRequiredSafetyWarnings(structured,evidence),evidenceReferenceSet(evidence)),usage=validateProviderUsage(result.usage);return{response,provider:"openai",model:IQ200_PHASE7_MODEL,usage}}}}
function controls(provider:HostedExecutionControls["provider"],overrides:Partial<HostedExecutionControls>={}):HostedExecutionControls{return{acquireLease:async()=>({token:"lease",ref:{}}),finishLease:async()=>{},reserve:async()=>({duplicate:false,inProgress:false,retryExhausted:false,retry:false,requestId:"request-1"}),loadPriorResult:async()=>({exists:false,success:false,interactionId:null,response:null}),persistSuccess:async()=>"interaction-1",persistFailure:async()=>{},buildEvidence:async()=>evidence,provider,withTimeout:async work=>work(new AbortController().signal),maxEvidenceChars:20000,timeoutMs:1000,now:()=>1000,...overrides}}

test("P8.1 deterministic valid hosted advisory completes the successful execution path",async()=>{const fixture=deterministicHostedResult(),events:string[]=[],persisted:Record<string,unknown>={};const result=await runHostedExecutionCore(controls(async()=>{events.push("provider");return fixture.run()},{acquireLease:async()=>{events.push("lease");return{token:"lease",ref:{}}},reserve:async()=>{events.push("reserve");return{duplicate:false,inProgress:false,retryExhausted:false,retry:false,requestId:"request-1"}},persistSuccess:async args=>{events.push("persistSuccess");Object.assign(persisted,args);return"interaction-1"},finishLease:async(_lease,outcome)=>{events.push(`finish:${outcome}`)}}),scope);assert.equal(fixture.calls(),1);assert.deepEqual(events,["lease","reserve","provider","persistSuccess","finish:SUCCEEDED"]);assert.equal(result.kind,"SUCCEEDED");assert.equal(persisted.requestId,"request-1");assert.equal(persisted.provider,"openai");assert.equal(persisted.model,IQ200_PHASE7_MODEL);assert.deepEqual(persisted.usage,{inputUnits:120,outputUnits:80});assert.deepEqual(persisted.response,result.response)});
test("P8.2 provider warning is preserved and server-required warnings are merged bounded and deduplicated",async()=>{const final=(await deterministicHostedResult().run()).response;assert.ok(final.safetyWarnings.includes("Preserve the provider warning."));assert.equal(final.safetyWarnings.filter(value=>value==="Wear approved eye protection.").length,1);assert.ok(final.safetyWarnings.some(value=>/high-pressure fuel/i.test(value)));assert.ok(final.safetyWarnings.length<=REASONING_ARRAY_MAX)});
test("P8.3 valid evidence references survive the full hosted validation sequence",async()=>{const final=(await deterministicHostedResult().run()).response;assert.deepEqual(final.evidenceUsed.map(item=>[item.category,item.reference]),[["CURRENT_JOB","CURRENT_JOB"],["KNOWN_FIX","KNOWN_FIX_1"]]);assert.deepEqual(final.hypotheses[0].evidenceReferences,["CURRENT_JOB","KNOWN_FIX_1"]);assert.equal(final.checks[0].evidenceSource,"KNOWN_FIX_1")});
test("P8.4 fabricated mismatched and duplicate evidence references fail closed",()=>{const allowed=evidenceReferenceSet(evidence);assert.throws(()=>validateReasoningResponse({...advisory(),evidenceUsed:[{category:"CURRENT_JOB",reference:"FOREIGN",detail:"x"}]},allowed));assert.throws(()=>validateReasoningResponse({...advisory(),evidenceUsed:[{category:"RELATED_HISTORY",reference:"CURRENT_JOB",detail:"x"}]},allowed));assert.throws(()=>validateReasoningResponse({...advisory(),evidenceUsed:[advisory().evidenceUsed[0],advisory().evidenceUsed[0]]},allowed))});
test("P8.5 successful usage is normalized and malformed usage fails closed",()=>{assert.deepEqual(validateProviderUsage({inputUnits:120,outputUnits:80}),{inputUnits:120,outputUnits:80});for(const usage of [{inputUnits:-1,outputUnits:1},{inputUnits:1.5,outputUnits:1},{inputUnits:"1",outputUnits:1},{inputUnits:1,outputUnits:1,rawCost:1}])assert.throws(()=>validateProviderUsage(usage))});
test("P8.6 hidden reasoning and provider-internal fields cannot enter or leave the structured response",()=>{for(const field of ["chainOfThought","chain_of_thought","reasoningText","internalReasoning","rawProviderResponse","providerEnvelope","systemPrompt"])assert.throws(()=>validateReasoningResponse({...advisory(),[field]:"hidden"}));assert.deepEqual(Object.keys(validateReasoningResponse(advisory())).sort(),responseKeys)});
test("P8.7 public success result is restricted to the intended hosted outcome and structured response",async()=>{const result=await runHostedExecutionCore(controls(async()=>deterministicHostedResult().run()),scope);if(result.kind!=="SUCCEEDED")assert.fail("expected successful hosted outcome");assert.deepEqual(Object.keys(result).sort(),["featureState","interactionId","kind","message","requestId","response","retried"]);assert.deepEqual(Object.keys(result.response).sort(),responseKeys);assert.equal(JSON.stringify(result).includes("OPENAI_API_KEY"),false);for(const field of forbiddenPersistenceFields)assert.equal(field in result,false)});
test("P8.8 successful persistence contract uses only approved interaction fields",()=>{const service=source("src/lib/iq200/hostedReasoningService.ts"),success=service.slice(service.indexOf("persistSuccess:"),service.indexOf("persistFailure:"));for(const field of ["companyId","jobId","sessionId","question","response","evidenceReferences","requestedBy","featureState","provider","model","usage","requestId","success:true","latencyMs","createdAt"])assert.ok(success.includes(field),field);assert.match(success,/batch\.create\(interaction/);assert.match(success,/batch\.update\(sessionRef,\{state:"REASONING_AVAILABLE",responseStatus:"STRUCTURED_RESPONSE"/);assert.match(success,/batch\.update\(requestRef,\{status:"SUCCEEDED",interactionId:interaction\.id/);assert.match(success,/batch\.update\(commissioningRef,\{status:"SUCCEEDED",interactionId:interaction\.id,model,usage,latencyMs/);for(const field of forbiddenPersistenceFields)assert.doesNotMatch(success,new RegExp(`\\b${field}\\b`,"i"),field)});
test("P8.9 hosted control success metadata cannot gain question prompt evidence envelope or credentials",()=>{const service=source("src/lib/iq200/hostedReasoningService.ts"),success=service.slice(service.indexOf("persistSuccess:"),service.indexOf("persistFailure:")),requestWrite=success.slice(success.indexOf("batch.update(requestRef"),success.indexOf("batch.update(commissioningRef")),commissioningWrite=success.slice(success.indexOf("batch.update(commissioningRef"));assert.match(requestWrite,/status:"SUCCEEDED",interactionId:interaction\.id/);assert.match(commissioningWrite,/status:"SUCCEEDED",interactionId:interaction\.id,model,usage,latencyMs/);for(const write of [requestWrite,commissioningWrite])assert.doesNotMatch(write,/scope\.question|response|evidence|prompt|envelope|api[_-]?key|authorization|bearer|secret|chain.?of.?thought|reasoningText|internalReasoning/i)});
test("P8.10 successful interaction and state changes remain one atomic batch",()=>{const service=source("src/lib/iq200/hostedReasoningService.ts"),success=service.slice(service.indexOf("persistSuccess:"),service.indexOf("persistFailure:"));assert.match(success,/adminDb\.batch\(\)/);assert.match(success,/batch\.create\(interaction/);assert.match(success,/batch\.update\(sessionRef/);assert.match(success,/batch\.update\(requestRef/);assert.match(success,/batch\.update\(commissioningRef/);assert.match(success,/await batch\.commit\(\)/)});
test("P8.11 API forwards only the validated service outcome with no cache storage",()=>{const route=source("src/app/api/iq200/jobs/[jobId]/sessions/[sessionId]/reason/route.ts");assert.match(route,/Response\.json\(await reasonAboutIQ200Session/);assert.match(route,/"cache-control":"no-store"/);assert.doesNotMatch(route,/OPENAI_API_KEY|authorization|providerEnvelope|rawProvider|systemPrompt|chain.?of.?thought/i)});
test("P8.12 current UI consumes every structured response section without raw HTML",()=>{const page=source("src/app/jobs/[id]/iq200/page.tsx");assert.match(page,/response:ReasoningResponse\|null/);assert.match(page,/setAssessment\(reasoning\.response\)/);for(const field of responseKeys)assert.match(page,new RegExp(`response\\.${field}\\b`),field);assert.doesNotMatch(page,/dangerouslySetInnerHTML|rawProviderResponse|providerEnvelope|systemPrompt|chain.?of.?thought/i)});
test("P8.13 actual hosted provider retains advisory schema safety evidence and usage validation",()=>{const provider=source("src/lib/iq200/hostedProvider.ts");assert.match(provider,/validateHostedAdvisoryResponse\(result\.response\)/);assert.match(provider,/validateReasoningResponse\(advisory\)/);assert.match(provider,/mergeRequiredSafetyWarnings\(structured,evidence\)/);assert.match(provider,/evidenceReferenceSet\(evidence\)/);assert.match(provider,/validateProviderUsage\(result\.usage\)/)});
test("P8.14 deterministic suite has no import or construction path to network transport",()=>{const self=source("tests/iq200-phase8.test.ts"),imports=self.slice(0,self.indexOf("const source")),fixture=self.slice(self.indexOf("function deterministicHostedResult"),self.indexOf("function controls"));assert.doesNotMatch(imports,/openaiTransport|hostedProvider|hostedReasoningService/);assert.doesNotMatch(fixture,/new OpenAI|fetch\(|process\.env|apiKey|authorization/i);assert.match(fixture,/const transport=\{send:async/)});
test("P8.15 commissioning remains closed even with otherwise complete valid staging configuration",()=>{const env={FLEETFIX_ENVIRONMENT:"staging",IQ200_PHASE7_COMMISSIONING_ENABLED:"false",IQ200_REASONING_ENABLED:"true",IQ200_HOSTED_PROVIDER_ENABLED:"true",IQ200_HOSTED_PROVIDER:"openai",IQ200_HOSTED_MODEL:IQ200_PHASE7_MODEL,IQ200_HOSTED_CREDENTIAL_PRESENT:"true",IQ200_PHASE7_COMPANY_ID:scope.companyId,IQ200_PHASE7_JOB_ID:scope.jobId,IQ200_PHASE7_SESSION_ID:scope.sessionId,IQ200_RATE_USER_PER_HOUR:"1",IQ200_RATE_COMPANY_PER_HOUR:"1",IQ200_RATE_SESSION_PER_HOUR:"1",IQ200_COMPANY_PERIOD_REQUESTS:"1",IQ200_LIMIT_PERIOD_SECONDS:"3600",IQ200_MAX_INPUT_CHARS:"20000",IQ200_MAX_OUTPUT_CHARS:"10000",IQ200_MAX_OUTPUT_TOKENS:"4096"},config=hostedReasoningConfig(env);assert.equal(IQ200_HOSTED_COMMISSIONING_ARMED,false);assert.equal(IQ200_PHASE7_COMMISSIONING_ARMED,false);assert.equal(config.environment,"staging");assert.equal(config.provider,"openai");assert.equal(config.credentialPresent,true);assert.ok(config.commissioningTarget);assert.ok(config.limits);assert.equal(config.commissioningEnabled,false);assert.equal(hostedExecutionAllowed(config),false);assert.equal(phase7ScopeAllowed(config,scope),false)});
test("P8.16 Phase 7 Retry 5 ledger namespace and one-request design remain unchanged",()=>{const service=source("src/lib/iq200/hostedReasoningService.ts"),control=source("src/lib/iq200/hostedControlCore.ts");assert.match(service,/ledger:"phase7_retry5",idempotencyNamespace:"phase7_retry5"/);assert.match(service,/PHASE7_RECOVERY_LEDGER_PATH="iq200_hosted_commissioning\/phase7_retry5"/);assert.match(service,/Date\.now\(\),1,PHASE7_RECOVERY_COMMISSIONING/);assert.match(control,/if\(Number\(count\)>=1\)throw new Error\("COMMISSIONING_LIMIT"\)/);assert.doesNotMatch(service,/retry6/i)});
