"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import QRCode from "qrcode";
import JsBarcode from "jsbarcode";
import { collection, doc, getDoc, getDocs } from "firebase/firestore";
import { clientDb } from "@/lib/firebaseClient";
import { COMPANY_ID } from "@/lib/company";
import { defaultInventoryLabelSettings, inventoryLabelFields, type InventoryLabelSettings } from "@/lib/inventoryLabels";
import { printLabelsInCleanWindow } from "@/lib/printLabels";

type Item = { id: string; partNumber?: string; description?: string; barcode?: string; category?: string; brand?: string; sellPrice?: number; costPrice?: number; grandTotal?: number; warehouseTotal?: number; vanTotal?: number; unit?: string; qrCodeUrl?: string; customFields?: Record<string, unknown>; labelQty?: number };
type Mode = "all" | "selected_on_hand" | "selected_custom" | "grv";
const num = (value: unknown, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const onHand = (item: Item) => Math.max(0, Math.floor(num(item.grandTotal, num(item.warehouseTotal) + num(item.vanTotal))));

function LabelCode({ type, value, showText, align = "center", widthMm, heightMm, offsetXMm, offsetYMm }: { type: "none" | "barcode" | "qr"; value: string; showText: boolean; align?: "left" | "center" | "right"; widthMm: number; heightMm: number; offsetXMm: number; offsetYMm: number }) {
  const svgRef = useRef<SVGSVGElement>(null), [qrUrl, setQrUrl] = useState("");
  useEffect(() => { if (!value || type === "none") return; if (type === "qr") void QRCode.toDataURL(value, { margin: 0, width: 160, errorCorrectionLevel: "M" }).then(setQrUrl); else if (svgRef.current) try { JsBarcode(svgRef.current, value, { format: "CODE128", displayValue: false, margin: 0, height: 34, width: 1.2 }); } catch { /* Invalid values are omitted. */ } }, [type, value]);
  if (type === "none" || !value) return null;
  const horizontalPosition = align === "left" ? { left: 0 } : align === "right" ? { right: 0 } : { left: "50%" };
  const centreShift = align === "center" ? "translateX(-50%) " : "";
  return <div className={`absolute bottom-0 z-10 flex flex-col overflow-visible ${align === "left" ? "items-start" : align === "right" ? "items-end" : "items-center"}`} style={{ ...horizontalPosition, transform: `${centreShift}translate(${offsetXMm}mm, ${offsetYMm}mm)` }}>{type === "qr" ? <img src={qrUrl} alt="QR code" className="object-contain" style={{ width: `${widthMm}mm`, height: `${heightMm}mm` }} /> : <svg ref={svgRef} aria-label="Barcode" style={{ width: `${widthMm}mm`, height: `${heightMm}mm`, maxWidth: "100%" }} />}{showText ? <span className="max-w-full truncate text-[0.65em] font-bold">{value}</span> : null}</div>;
}

export default function InventoryLabelsPage() {
  const [items, setItems] = useState<Item[]>([]), [settings, setSettings] = useState<InventoryLabelSettings>(defaultInventoryLabelSettings);
  const [mode, setMode] = useState<Mode>("selected_on_hand"), [selected, setSelected] = useState<Record<string, boolean>>({}), [quantities, setQuantities] = useState<Record<string, number>>({}), [search, setSearch] = useState("");
  useEffect(() => {
    const payload = localStorage.getItem("fleetfix-grv-label-items");
    if (payload) try { const parsed = JSON.parse(payload) as Item[]; setItems(parsed); setSelected(Object.fromEntries(parsed.map((item) => [item.id, true]))); setQuantities(Object.fromEntries(parsed.map((item) => [item.id, Math.max(0, Math.floor(num(item.labelQty)))]))); setMode("grv"); } catch { /* fall back to inventory */ }
    localStorage.removeItem("fleetfix-grv-label-items");
    Promise.all([getDocs(collection(clientDb, "companies", COMPANY_ID, "inventory")), getDoc(doc(clientDb, "companies", COMPANY_ID, "inventory_settings", "stock_labels"))]).then(([stock, setup]) => { if (!payload) setItems(stock.docs.map((entry) => ({ id: entry.id, ...entry.data() } as Item))); if (setup.exists()) setSettings({ ...defaultInventoryLabelSettings, ...setup.data() } as InventoryLabelSettings); });
  }, []);
  useEffect(() => { if (mode === "all") setSelected(Object.fromEntries(items.filter((item) => onHand(item) > 0).map((item) => [item.id, true]))); }, [mode, items]);
  const filtered = items.filter((item) => `${item.partNumber || ""} ${item.description || ""} ${item.barcode || ""}`.toLowerCase().includes(search.toLowerCase()));
  const labels = useMemo(() => items.flatMap((item) => { if (!selected[item.id]) return []; const qty = mode === "all" || mode === "selected_on_hand" ? onHand(item) : Math.max(0, Math.floor(num(quantities[item.id]))); return Array.from({ length: qty }, (_, copy) => ({ ...item, copy, stockQty: onHand(item) })); }), [items, mode, quantities, selected]);
  const value = (item: Item & { stockQty: number }, key: string) => key.startsWith("custom:") ? String(item.customFields?.[key.slice(7)] ?? "") : key === "sellPrice" || key === "costPrice" ? `R ${num(item[key]).toFixed(2)}` : String((item as Record<string, unknown>)[key] ?? "");
  const label = (key: string) => inventoryLabelFields.find(([id]) => id === key)?.[1] || key.replace("custom:", "");
  const configuredFields = settings.fields?.length ? settings.fields : (settings.fieldOrder || []).filter((source) => source !== "barcode").map((source) => ({ id: source, source, caption: label(source), showCaption: true, align: "left" as const, fontSizePt: settings.fontSizePt }));
  const orderedElements: Array<{ kind: "field"; field: InventoryLabelSettings["fields"][number] } | { kind: "code" }> = configuredFields.map((field) => ({ kind: "field", field }));
  orderedElements.splice(Math.min(Math.max(settings.codeOrder ?? configuredFields.length, 0), configuredFields.length), 0, { kind: "code" });
  const codeValue = (item: Item & { stockQty: number }) => (settings.codeFields || ["partNumber"]).map((key) => value(item, key)).filter(Boolean).join(" | ");
  const pageWidth = settings.mediaType === "roll" ? settings.labelWidthMm : settings.pageWidthMm, pageHeight = settings.mediaType === "roll" ? settings.labelHeightMm : settings.pageHeightMm;
  return <main className="inventory-label-print-page min-h-screen bg-[#f4f7fb] p-5 print:bg-white print:p-0"><style>{`@media print{@page{size:${pageWidth}mm ${pageHeight}mm;margin:0}.inventory-label-print-page{position:absolute!important;left:0!important;top:0!important}.label-grid{display:${settings.mediaType === "roll" ? "block" : "grid"}!important;grid-template-columns:repeat(${Math.max(1, settings.columns)},${settings.labelWidthMm}mm)!important;gap:${settings.gapYMm}mm ${settings.gapXMm}mm!important;padding:${settings.mediaType === "roll" ? 0 : settings.marginMm}mm!important}.stock-label{break-inside:avoid;page-break-inside:avoid;flex:none!important}${settings.mediaType === "roll" ? ".stock-label+.stock-label{break-before:page;page-break-before:always}" : ""}}`}</style><div className="mx-auto max-w-[1800px] print:max-w-none">
    <header className="mb-5 flex flex-wrap items-end justify-between gap-4 print:hidden"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">Inventory</p><h1 className="text-4xl font-black">Print Stock Labels</h1><p className="text-sm text-gray-500">Select stock and label quantities. The saved Admin template controls the output.</p></div><div className="flex gap-2"><button onClick={() => history.back()} className="rounded-xl border bg-white px-5 py-3 font-bold">Back</button><button disabled={!labels.length} onClick={() => printLabelsInCleanWindow(".label-grid", pageWidth, pageHeight, settings.mediaType === "roll")} className="rounded-xl bg-blue-600 px-6 py-3 font-black text-white disabled:opacity-40">Print {labels.length} Label{labels.length === 1 ? "" : "s"}</button></div></header>
    <section className="mb-5 grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-4 print:hidden">{[["all", "All stock — quantity on hand"], ["selected_on_hand", "Selected — quantity on hand"], ["selected_custom", "Selected — enter label quantity"]].map(([id, text]) => <label key={id} className="flex cursor-pointer items-center gap-2 rounded-xl border p-3 font-bold"><input type="radio" checked={mode === id} onChange={() => setMode(id as Mode)} />{text}</label>)}<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search stock..." className="rounded-xl border px-4" /></section>
    <section className="mb-6 max-h-[45vh] overflow-auto rounded-2xl border bg-white shadow-sm print:hidden"><table className="w-full text-sm"><thead className="sticky top-0 bg-gray-50"><tr><th className="p-3 text-left">Print</th><th className="p-3 text-left">Part Number</th><th className="p-3 text-left">Description</th><th className="p-3 text-right">On Hand</th><th className="p-3 text-right">Labels</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-t"><td className="p-3"><input type="checkbox" checked={!!selected[item.id]} disabled={mode === "all" || mode === "grv"} onChange={(event) => setSelected((current) => ({ ...current, [item.id]: event.target.checked }))} /></td><td className="p-3 font-black text-blue-700">{item.partNumber || "—"}</td><td className="p-3">{item.description || "—"}</td><td className="p-3 text-right font-bold">{onHand(item)}</td><td className="p-3 text-right"><input type="number" min="0" step="1" disabled={mode !== "selected_custom"} value={mode === "all" || mode === "selected_on_hand" ? onHand(item) : quantities[item.id] ?? 0} onChange={(event) => setQuantities((current) => ({ ...current, [item.id]: Math.max(0, Number(event.target.value)) }))} className="w-24 rounded-lg border px-3 py-2 text-right disabled:bg-gray-100" /></td></tr>)}</tbody></table></section>
    <div className="label-grid grid justify-start bg-white">{labels.map((item) => <article key={`${item.id}-${item.copy}`} className="stock-label relative flex flex-col justify-center overflow-hidden bg-white" style={{ width: `${settings.labelWidthMm}mm`, height: `${settings.labelHeightMm}mm`, padding: `${settings.marginMm}mm`, border: settings.showBorder ? "0.25mm solid #111" : "none", fontSize: `${settings.fontSizePt}pt`, fontFamily: settings.fontFamily ?? defaultInventoryLabelSettings.fontFamily, color: settings.textColor ?? "#000000", lineHeight: 1.15 }}>{orderedElements.map((element, index) => { if (element.kind === "code") return <LabelCode key="label-code" type={settings.codeType || "none"} value={codeValue(item)} showText={settings.showCodeText !== false} align={settings.codeAlign} widthMm={settings.codeWidthMm ?? 12} heightMm={settings.codeHeightMm ?? 12} offsetXMm={settings.codeOffsetXMm ?? 0} offsetYMm={settings.codeOffsetYMm ?? 0} />; const field = element.field; const text = value(item, field.source); return text ? <div key={`${field.id}-${index}`} className={`${field.source === "partNumber" ? "font-black" : "font-semibold"} ${field.align === "center" ? "text-center" : field.align === "right" ? "text-right" : "text-left"} min-w-0 whitespace-normal break-words`} style={{ fontSize: `${field.fontSizePt ?? settings.fontSizePt}pt`, fontFamily: field.fontFamily ?? settings.fontFamily, color: field.textColor ?? settings.textColor, backgroundColor: field.backgroundColor && field.backgroundColor !== "transparent" ? field.backgroundColor : undefined, paddingRight: settings.codeType !== "none" && settings.codeAlign !== "left" ? `${(settings.codeWidthMm ?? 12) + 1}mm` : undefined, paddingLeft: settings.codeType !== "none" && settings.codeAlign === "left" ? `${(settings.codeWidthMm ?? 12) + 1}mm` : undefined, transform: `translate(${field.offsetXMm ?? 0}mm, ${field.offsetYMm ?? 0}mm)` }}>{field.showCaption !== false ? <span className="text-[0.72em] font-bold uppercase text-gray-500">{field.caption}: </span> : null}{text}</div> : null; })}</article>)}</div>
  </div></main>;
}
