export type HostedFailure="DISABLED"|"RATE_LIMITED"|"COMPANY_LIMIT"|"TIMEOUT"|"PROVIDER_UNAVAILABLE"|"PROVIDER_AUTH"|"INVALID_PROVIDER_RESPONSE"|"SAFETY_VALIDATION_FAILED"|"STORAGE_FAILURE"|"CONFIGURATION_ERROR";
export type HostedValidationReason="ENVELOPE_NOT_OBJECT"|"ENVELOPE_STATUS_INCOMPLETE"|"ENVELOPE_INCOMPLETE_MAX_OUTPUT_TOKENS"|"ENVELOPE_STATUS_FAILED"|"ENVELOPE_STATUS_CANCELLED"|"ENVELOPE_STATUS_QUEUED"|"ENVELOPE_STATUS_OTHER"|"ENVELOPE_OUTPUT_EMPTY"|"ENVELOPE_OUTPUT_TYPE"|"ENVELOPE_REASONING_ONLY"|"ENVELOPE_REFUSAL"|"OUTPUT_TEXT_MISSING"|"OUTPUT_TEXT_BLANK"|"OUTPUT_TEXT_TOO_LARGE"|"JSON_PARSE"|"RESPONSE_SIZE_LIMIT"|"RESPONSE_SHAPE"|"SUMMARY_EMPTY"|"STRING_LIMIT"|"ARRAY_ITEM_EMPTY"|"ARRAY_LIMIT"|"UNSAFE_MARKUP"|"CONFIDENCE_INVALID"|"EVIDENCE_UNKNOWN"|"EVIDENCE_CATEGORY_MISMATCH"|"EVIDENCE_DUPLICATE"|"USAGE_INVALID";
export type HostedSafetyReason="PROHIBITED_ACTION"|"UNQUALIFIED_REPAIR_ACTION";
export function isHostedSafetyReason(value:unknown):value is HostedSafetyReason{return value==="PROHIBITED_ACTION"||value==="UNQUALIFIED_REPAIR_ACTION"}
export class HostedSafetyValidationError extends Error{readonly safetyReason:HostedSafetyReason;constructor(safetyReason:HostedSafetyReason){super("SAFETY_VALIDATION_FAILED");this.safetyReason=safetyReason}}
export class HostedProviderError extends Error{readonly category:HostedFailure;readonly validationReason:HostedValidationReason|null;readonly safetyReason:HostedSafetyReason|null;constructor(category:HostedFailure,validationReason:HostedValidationReason|null=null,safetyReason:HostedSafetyReason|null=null){super(category);this.category=category;this.validationReason=validationReason;this.safetyReason=safetyReason}}
export class HostedTransportHttpError extends Error{readonly status:number;constructor(status:number){super("HOSTED_TRANSPORT_HTTP_ERROR");this.status=status}}
export function safeHostedFailure(error:unknown,aborted=false):HostedFailure{if(error instanceof HostedProviderError)return error.category;if(aborted)return"TIMEOUT";if(error instanceof HostedTransportHttpError){if(error.status===401||error.status===403)return"PROVIDER_AUTH";if(error.status===429)return"RATE_LIMITED";if(error.status>=500)return"PROVIDER_UNAVAILABLE"}return"PROVIDER_UNAVAILABLE"}
export const HOSTED_REASONING_TIMEOUT_MS=30_000;
export async function withHostedAbortTimeout<T>(work:(signal:AbortSignal)=>Promise<T>,timeoutMs=HOSTED_REASONING_TIMEOUT_MS){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await work(controller.signal)}catch(error){const category=safeHostedFailure(error,controller.signal.aborted),validationReason=category==="INVALID_PROVIDER_RESPONSE"&&error instanceof HostedProviderError?error.validationReason:null,safetyReason=category==="SAFETY_VALIDATION_FAILED"&&error instanceof HostedProviderError?error.safetyReason:null;throw new HostedProviderError(category,validationReason,safetyReason)}finally{clearTimeout(timer)}}
