import "server-only";
import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { adminDb } from "@/lib/firebaseAdmin"; import { effectivePermissions } from "@/lib/permissions"; import { ServerAccessError, type ServerUserContext } from "@/lib/serverAuth";
import { authorisedJob } from "./service"; import { KNOWN_FIX_ID, KNOWN_FIX_MAX_CANDIDATES, knownFixApprovalReadiness, knownFixEditBehavior, knownFixMatch, knownFixTransitionAllowed, parseKnownFixSearch, parseStoredKnownFix, validateKnownFixInput, type JobApplicability, type StoredKnownFix } from "./knownFixCore"; import { normalizeFaultCode, normalizeLabel } from "./historyCore";

const collectionFor = (companyId: string) => adminDb.collection(`companies/${companyId}/iq200_known_fixes`);
function requirePermission(context: ServerUserContext, permission: string) { if (effectivePermissions(context.companyUser)[permission] !== true) throw new ServerAccessError("FORBIDDEN", `${permission} permission is required.`, 403); }
function iso(value: unknown) { return value instanceof Timestamp ? value.toDate().toISOString() : value && typeof value === "object" && "toDate" in value && typeof value.toDate === "function" ? value.toDate().toISOString() : null; }
function adminDto(id: string, data: StoredKnownFix) { return { id, title: data.title, category: data.category, status: data.status, active: data.active === true, vehicleMake: data.vehicleMake, vehicleModel: data.vehicleModel, vehicleType: data.vehicleType, engineFamily: data.engineFamily, otherApplicability: data.otherApplicability, systemComponent: data.systemComponent, symptoms: data.symptoms, faultCodes: data.faultCodes, diagnosticProcedure: data.diagnosticProcedure, expectedValues: data.expectedValues, findingsConditions: data.findingsConditions, repairProcedure: data.repairProcedure, requiredTools: data.requiredTools, partsComponents: data.partsComponents, safetyWarnings: data.safetyWarnings, technicalCautions: data.technicalCautions, notes: data.notes, sourceReference: data.sourceReference, relatedHistoricalJobIds: data.relatedHistoricalJobIds, revision: data.revision, createdBy: data.createdBy, createdAt: iso(data.createdAt), updatedBy: data.updatedBy, updatedAt: iso(data.updatedAt), approvedBy: data.approvedBy, approvedAt: iso(data.approvedAt) }; }
function technicianDto(id: string, data: StoredKnownFix, match: { score: number; reasons: string[] }) { const value = adminDto(id, data); return { id: value.id, title: value.title, category: value.category, vehicleMake: value.vehicleMake, vehicleModel: value.vehicleModel, vehicleType: value.vehicleType, engineFamily: value.engineFamily, systemComponent: value.systemComponent, symptoms: value.symptoms, faultCodes: value.faultCodes, diagnosticProcedure: value.diagnosticProcedure, expectedValues: value.expectedValues, findingsConditions: value.findingsConditions, repairProcedure: value.repairProcedure, requiredTools: value.requiredTools, partsComponents: value.partsComponents, safetyWarnings: value.safetyWarnings, technicalCautions: value.technicalCautions, notes: value.notes, sourceReference: value.sourceReference, revision: value.revision, relevanceScore: match.score, relevanceReasons: match.reasons }; }
export async function searchKnownFixesForJob(context: ServerUserContext, jobId: string, requestUrl: string) { let search; try { search = parseKnownFixSearch(new URL(requestUrl)); } catch { throw new ServerAccessError("INVALID_INPUT", "Known Fix search filters are invalid.", 400); } const { data } = await authorisedJob(context, jobId); const vehicle = data.vehicle || data.vehicleDetails || {}; const job: JobApplicability = { make: normalizeLabel(data.vehicleMake || vehicle.make), model: normalizeLabel(data.vehicleModel || vehicle.model), vehicleType: normalizeLabel(data.vehicleType || vehicle.type), engineFamily: normalizeLabel(data.engineFamily || data.engineModel), faultCodes: [...(Array.isArray(data.faultCodes) ? data.faultCodes : []), data.faultCode].map(normalizeFaultCode).filter(Boolean), text: String(data.complaint || data.description || data.reportedFault || "") }; const snapshot = await collectionFor(context.companyId).where("status", "==", "APPROVED").limit(KNOWN_FIX_MAX_CANDIDATES).get(); const results = snapshot.docs.filter((doc) => doc.data().active === true).map((doc) => ({ doc, data: parseStoredKnownFix(doc.data(), context.companyId) })).filter((item) => item.data).map((item) => ({ ...item, match: knownFixMatch(job, item.data!, search) })).filter((item) => item.match).sort((a, b) => b.match!.score - a.match!.score).slice(0, search.limit).map((item) => technicianDto(item.doc.id, item.data!, item.match!)); return { results }; }
export async function listKnownFixes(context: ServerUserContext) { const permissions = effectivePermissions(context.companyUser); const capabilities = { view: permissions["View IQ200 Known Fixes"] === true, manage: permissions["Manage IQ200 Known Fixes"] === true, approve: permissions["Approve IQ200 Known Fixes"] === true }; if (!capabilities.view && !capabilities.manage && !capabilities.approve) throw new ServerAccessError("FORBIDDEN", "Known Fix administrative permission is required.", 403); const snapshot = await collectionFor(context.companyId).limit(100).get(); const fixes = snapshot.docs.map((doc) => ({ id: doc.id, data: parseStoredKnownFix(doc.data(), context.companyId) })).filter((item) => item.data).map((item) => adminDto(item.id, item.data!)); return { fixes, capabilities: { ...capabilities, view: true } }; }
export async function createKnownFix(context: ServerUserContext, input: unknown) { requirePermission(context, "Manage IQ200 Known Fixes"); let data; try { data = validateKnownFixInput(input); } catch { throw new ServerAccessError("INVALID_INPUT", "Known Fix content is invalid or exceeds limits.", 400); } const ref = collectionFor(context.companyId).doc(); await ref.create({ ...data, companyId: context.companyId, status: "DRAFT", active: false, revision: 1, createdBy: context.uid, createdAt: FieldValue.serverTimestamp(), updatedBy: context.uid, updatedAt: FieldValue.serverTimestamp(), approvedBy: null, approvedAt: null }); const stored = parseStoredKnownFix((await ref.get()).data(), context.companyId); if (!stored) throw new ServerAccessError("CONFLICT", "The Known Fix could not be read after saving.", 409); return { fix: adminDto(ref.id, stored) }; }
export async function updateKnownFix(context: ServerUserContext, id: string, input: unknown) {
    requirePermission(context, "Manage IQ200 Known Fixes");
    if (!KNOWN_FIX_ID.test(id)) throw new ServerAccessError("NOT_FOUND", "Known Fix not found.", 404);
    let data;
    try { data = validateKnownFixInput(input); }
    catch { throw new ServerAccessError("INVALID_INPUT", "Known Fix content is invalid or exceeds limits.", 400); }
    const ref = collectionFor(context.companyId).doc(id);
    await adminDb.runTransaction(async (transaction) => { const snap = await transaction.get(ref); const stored = snap.exists ? parseStoredKnownFix(snap.data(), context.companyId) : null; if (!stored) throw new ServerAccessError("NOT_FOUND", "Known Fix not found.", 404); const editBehavior = knownFixEditBehavior(stored.status); if (editBehavior === "denied") throw new ServerAccessError("INACTIVE_KNOWN_FIX_LOCKED", "This Known Fix is inactive and cannot be edited.", 409); transaction.update(ref, { ...data, status: "DRAFT", active: false, revision: editBehavior === "revision" ? Number(stored.revision) + 1 : stored.revision, updatedBy: context.uid, updatedAt: FieldValue.serverTimestamp(), approvedBy: null, approvedAt: null }); });
    const stored = parseStoredKnownFix((await ref.get()).data(), context.companyId); if (!stored) throw new ServerAccessError("CONFLICT", "The Known Fix could not be read after saving.", 409); return { fix: adminDto(id, stored) };
}
export async function changeKnownFixStatus(context: ServerUserContext, id: string, action: string) { if (!KNOWN_FIX_ID.test(id)) throw new ServerAccessError("NOT_FOUND", "Known Fix not found.", 404); if (action === "approve") requirePermission(context, "Approve IQ200 Known Fixes"); else if (action === "inactivate") requirePermission(context, "Manage IQ200 Known Fixes"); else throw new ServerAccessError("INVALID_INPUT", "Known Fix action is invalid.", 400); const ref = collectionFor(context.companyId).doc(id); await adminDb.runTransaction(async (transaction) => { const snap = await transaction.get(ref); const stored = snap.exists ? parseStoredKnownFix(snap.data(), context.companyId) : null; if (!stored) throw new ServerAccessError("NOT_FOUND", "Known Fix not found.", 404); if (!knownFixTransitionAllowed(stored.status, action)) throw new ServerAccessError("INVALID_KNOWN_FIX_TRANSITION", "The Known Fix cannot perform that lifecycle transition.", 409); if (action === "approve") { const readiness = knownFixApprovalReadiness(stored); if (!readiness.ready) throw new ServerAccessError("KNOWN_FIX_NOT_READY_FOR_APPROVAL", `Known Fix approval requires: ${readiness.missing.join(", ")}.`, 422); transaction.update(ref, { status: "APPROVED", active: true, approvedBy: context.uid, approvedAt: FieldValue.serverTimestamp(), updatedBy: context.uid, updatedAt: FieldValue.serverTimestamp() }); } else transaction.update(ref, { status: "INACTIVE", active: false, updatedBy: context.uid, updatedAt: FieldValue.serverTimestamp() }); }); const stored = parseStoredKnownFix((await ref.get()).data(), context.companyId); if (!stored) throw new ServerAccessError("CONFLICT", "The Known Fix could not be read after saving.", 409); return { fix: adminDto(id, stored) }; }
