import "server-only";
import { FieldValue, type DocumentData } from "firebase-admin/firestore";
import { adminDb } from "@/lib/firebaseAdmin";
import { ServerAccessError, type ServerUserContext } from "@/lib/serverAuth";
import { searchIQ200History } from "./historyService";
import { searchKnownFixesForJob } from "./knownFixService";
import { configuredReasoningProvider } from "./reasoningProvider";
import { getIQ200JobContext, authorisedJob } from "./service";
import { hostedExecutionAllowed } from "./hostedConfig";
import { getHostedReasoningServerConfig } from "./hostedServerConfig";
import { runHostedReasoning } from "./hostedReasoningService";
import { REASONING_DIAGNOSTICS_MAX, REASONING_HISTORY_MAX, REASONING_ID, REASONING_KNOWN_FIX_MAX, REASONING_NOTES_MAX, REASONING_RECENT_INTERACTIONS_MAX, ReasoningInProgressError, evidenceReferenceSet, mergeRequiredSafetyWarnings, reasoningEnabled, validateProviderUsage, validateReasoningQuestion, validateReasoningResponse, withReasoningLock, withReasoningTimeout, type Confidence, type ReasoningEvidence } from "./reasoningCore";

const safeText=(value:unknown,max=1000)=>typeof value==="string"?value.trim().slice(0,max):"";
const safeStrings=(value:unknown,count:number,max=500)=>Array.isArray(value)?value.flatMap(item=>typeof item==="string"?[safeText(item,max)]:[]).filter(Boolean).slice(0,count):[];
function validateId(value:string){if(!REASONING_ID.test(value))throw new ServerAccessError("NOT_FOUND","IQ200 session not found.",404)}

// Every field below is untrusted evidence data. Hosted providers must preserve
// this typed boundary and must not concatenate evidence into system/developer policy.
export async function evidencePackage(context:ServerUserContext,jobId:string,currentData:DocumentData,sessionRef:FirebaseFirestore.DocumentReference,question:string):Promise<ReasoningEvidence>{
 const[jobContext,history,knownFixes,recent]=await Promise.all([getIQ200JobContext(context,jobId),searchIQ200History(context,jobId,`http://iq200.local/history?limit=${REASONING_HISTORY_MAX}`),searchKnownFixesForJob(context,jobId,`http://iq200.local/known-fixes?limit=${REASONING_KNOWN_FIX_MAX}`),sessionRef.collection("interactions").orderBy("createdAt","desc").limit(REASONING_RECENT_INTERACTIONS_MAX).get()]);
 const job=jobContext.job,diagnostics=Array.isArray(job.diagnostics)?job.diagnostics:[];
 return{question,currentJob:{jobNumber:safeText(job.number,128),status:safeText(job.status,100),vehicle:{make:safeText(job.vehicle.make,100),model:safeText(job.vehicle.model,100),type:safeText(job.vehicle.type,100),engineFamily:safeText(currentData.engineFamily||currentData.engineModel,100),descriptor:[job.vehicle.registrationNumber,job.vehicle.fleetNumber].map(value=>safeText(value,100)).filter(Boolean).join(" / ")},complaint:safeText(job.description,2000),faultCodes:[...diagnostics.map(item=>safeText((item as DocumentData)?.code,64)),...safeStrings(currentData.faultCodes,20,64),safeText(currentData.faultCode,64)].filter(Boolean).slice(0,20),notes:(Array.isArray(job.notes)?job.notes:[]).map(item=>safeText((item as DocumentData)?.text,1000)).filter(Boolean).slice(0,REASONING_NOTES_MAX),diagnostics:diagnostics.map(item=>[safeText((item as DocumentData)?.code,64),safeText((item as DocumentData)?.description,500),safeText((item as DocumentData)?.value,100)].filter(Boolean).join(": ")).filter(Boolean).slice(0,REASONING_DIAGNOSTICS_MAX)},relatedHistory:history.results.slice(0,REASONING_HISTORY_MAX).map((item,index)=>({reference:`HISTORY_${index+1}`,description:`Job ${safeText(item.jobNumber,128)}: ${safeText(item.description,1000)}`,faultCodes:safeStrings(item.faultCodes,20,64),findings:safeStrings(item.technicianFindings,8),repairs:safeStrings(item.repairPerformed,8),relevanceReasons:safeStrings(item.relevanceReasons,5,300)})),approvedKnownFixes:knownFixes.results.slice(0,REASONING_KNOWN_FIX_MAX).map((item,index)=>({reference:`KNOWN_FIX_${index+1}`,title:safeText(item.title,160),applicability:[item.vehicleMake,item.vehicleModel,item.vehicleType,item.engineFamily].map(value=>safeText(value,100)).filter(Boolean).join(" / ")||"Generic",faultCodes:safeStrings(item.faultCodes,20,64),diagnosticProcedure:safeText(item.diagnosticProcedure,2000),expectedValues:safeText(item.expectedValues,1000),safetyWarnings:safeText(item.safetyWarnings,1000),technicalCautions:safeText(item.technicalCautions,1000),relevanceReasons:safeStrings(item.relevanceReasons,5,300)})),recentInteractions:recent.docs.map(doc=>{const data=doc.data();return{question:safeText(data.question,2000),summary:safeText(data.response?.summary,1000),confidence:(["LOW","MEDIUM","HIGH"].includes(data.response?.confidence)?data.response.confidence:"LOW") as Confidence}})};
}

export async function reasonAboutIQ200Session(context:ServerUserContext,jobId:string,sessionId:string,input:unknown){
 validateId(sessionId);
 const{snapshot:job,data:currentData}=await authorisedJob(context,jobId),sessionRef=job.ref.collection("iq200_sessions").doc(sessionId),session=await sessionRef.get(),data=session.data();
 if(!session.exists||data?.companyId!==context.companyId||data?.jobId!==job.id)throw new ServerAccessError("NOT_FOUND","IQ200 session not found.",404);
 let question:string;try{question=validateReasoningQuestion(input)}catch{throw new ServerAccessError("INVALID_INPUT","Enter a plain-text question of no more than 2,000 characters.",400)}
 const hostedConfig=getHostedReasoningServerConfig();
 if(hostedExecutionAllowed(hostedConfig))return runHostedReasoning(context,jobId,sessionId,question,currentData,sessionRef);
 if(!reasoningEnabled())return{featureState:"DISABLED",message:"IQ200 reasoning is not enabled. Job history and approved Known Fixes remain available.",response:null};
 const lock=`${context.companyId}:${job.id}:${session.id}`;
 try{return await withReasoningLock(lock,async()=>{const started=Date.now(),interaction=sessionRef.collection("interactions").doc();try{const evidence=await evidencePackage(context,jobId,currentData,sessionRef,question),provider=configuredReasoningProvider(),result=await withReasoningTimeout(provider.reason(evidence)),allowed=evidenceReferenceSet(evidence),validated=validateReasoningResponse(result.response,allowed),response=validateReasoningResponse(mergeRequiredSafetyWarnings(validated,evidence),allowed),usage=validateProviderUsage(result.usage);const batch=adminDb.batch();batch.create(interaction,{companyId:context.companyId,jobId:job.id,sessionId:session.id,question,response,evidenceReferences:response.evidenceUsed,requestedBy:context.uid,featureState:"TEST_ENABLED",provider:result.provider,model:result.model,usage,success:true,latencyMs:Date.now()-started,createdAt:FieldValue.serverTimestamp()});batch.update(sessionRef,{state:"REASONING_AVAILABLE",responseStatus:"STRUCTURED_RESPONSE",updatedAt:FieldValue.serverTimestamp()});await batch.commit();return{featureState:"TEST_ENABLED",message:"Deterministic test reasoning generated.",interactionId:interaction.id,response};}catch(error){const errorClass=error instanceof Error&&error.message==="INVALID_PROVIDER_RESPONSE"?"INVALID_RESPONSE":error instanceof Error&&error.message==="PROVIDER_TIMEOUT"?"TIMEOUT":"PROVIDER_FAILURE";await interaction.create({companyId:context.companyId,jobId:job.id,sessionId:session.id,question,requestedBy:context.uid,featureState:"TEST_ENABLED",provider:"deterministic-test",success:false,errorClass,latencyMs:Date.now()-started,createdAt:FieldValue.serverTimestamp()});throw new ServerAccessError("REASONING_UNAVAILABLE","IQ200 reasoning is temporarily unavailable. Job history and approved Known Fixes remain available.",503)}})}catch(error){if(error instanceof ReasoningInProgressError)throw new ServerAccessError("REQUEST_IN_PROGRESS","An IQ200 reasoning request is already in progress for this session.",429);throw error}
}
