"use client";
import Link from "next/link"; import { useCallback, useEffect, useMemo, useState } from "react"; import { iq200Api } from "@/lib/iq200/client";
type Fix={id:string;title:string;status:string;vehicleMake:string;vehicleModel:string;vehicleType:string;systemComponent:string;faultCodes:string[];revision:number;createdBy:string;createdAt:string|null;updatedBy:string;updatedAt:string|null;approvedBy:string;approvedAt:string|null}&Record<string,unknown>;
const arrayFields=["symptoms","faultCodes","requiredTools","partsComponents","relatedHistoricalJobIds"];
const longFields=["diagnosticProcedure","expectedValues","findingsConditions","repairProcedure","safetyWarnings","technicalCautions","notes","sourceReference"];
const keys=["title","category","vehicleMake","vehicleModel","vehicleType","engineFamily","otherApplicability","systemComponent","symptoms","faultCodes",...longFields,"requiredTools","partsComponents","relatedHistoricalJobIds"];
const blank=Object.fromEntries(keys.map(key=>[key,""])) as Record<string,string>;
export default function KnownFixAdmin(){
 const[fixes,setFixes]=useState<Fix[]>([]),[form,setForm]=useState({...blank}); const[caps,setCaps]=useState({view:false,manage:false,approve:false}); const[editing,setEditing]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[vehicle,setVehicle]=useState(""),[component,setComponent]=useState(""),[faultCode,setFaultCode]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const result=await iq200Api<{fixes:Fix[];capabilities:typeof caps}>("/api/iq200/known-fixes");setFixes(result.fixes);setCaps(result.capabilities);setError("")}catch(e){setError(e instanceof Error?e.message:"Known Fixes unavailable")}},[]); useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>fixes.filter(f=>(!status||f.status===status)&&`${f.title} ${f.vehicleMake} ${f.vehicleModel} ${f.vehicleType} ${f.systemComponent} ${f.faultCodes.join(" ")}`.toLowerCase().includes(search.toLowerCase())&&`${f.vehicleMake} ${f.vehicleModel} ${f.vehicleType}`.toLowerCase().includes(vehicle.toLowerCase())&&f.systemComponent.toLowerCase().includes(component.toLowerCase())&&f.faultCodes.join(" ").toLowerCase().includes(faultCode.toLowerCase())),[fixes,status,search,vehicle,component,faultCode]);
 const payload=()=>Object.fromEntries(Object.entries(form).map(([key,value])=>[key,arrayFields.includes(key)?value.split("\n").map(item=>item.trim()).filter(Boolean):value]));
 const save=async()=>{try{await iq200Api(editing?`/api/iq200/known-fixes/${editing}`:"/api/iq200/known-fixes",{method:editing?"PATCH":"POST",body:JSON.stringify(payload())});setEditing("");setForm({...blank});await load()}catch(e){setError(e instanceof Error?e.message:"Save failed")}};
 const action=async(id:string,value:string)=>{try{await iq200Api(`/api/iq200/known-fixes/${id}`,{method:"PATCH",body:JSON.stringify({action:value})});await load()}catch(e){setError(e instanceof Error?e.message:"Action failed")}};
 const edit=(fix:Fix)=>{setEditing(fix.id);setForm(Object.fromEntries(keys.map(key=>[key,Array.isArray(fix[key])?(fix[key] as string[]).join("\n"):String(fix[key]||"")])))};
 return <main className="min-h-screen bg-[#f5f7fb] p-4 md:p-7"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-blue-600">Admin / IQ200</p><h1 className="text-3xl font-black">Known Fixes</h1><p className="text-sm text-slate-500">Curated technical knowledge with explicit approval.</p></div><Link href="/admin" className="rounded-xl border bg-white px-5 py-3 font-bold">Back</Link></header>{error&&<p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{caps.manage&&<section className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">{editing?"Edit draft / create revision":"Create draft"}</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{keys.map(key=><label key={key} className={`text-xs font-black uppercase text-slate-500 ${longFields.includes(key)?"md:col-span-2":""}`}>{key.replace(/([A-Z])/g," $1")}<textarea rows={longFields.includes(key)?4:2} value={form[key]} onChange={event=>setForm(value=>({...value,[key]:event.target.value}))} className="mt-1 w-full rounded-xl border p-3 font-normal normal-case text-slate-800"/></label>)}</div><button onClick={()=>void save()} className="mt-4 rounded-xl bg-blue-600 px-5 py-3 font-black text-white">Save as Draft</button></section>}
 {caps.view&&<section className="rounded-3xl border bg-white p-5"><div className="grid gap-3 md:grid-cols-3"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search all knowledge" className="rounded-xl border p-3"/><select value={status} onChange={event=>setStatus(event.target.value)} className="rounded-xl border p-3"><option value="">All statuses</option><option>DRAFT</option><option>APPROVED</option><option>INACTIVE</option></select><input value={vehicle} onChange={event=>setVehicle(event.target.value)} placeholder="Make, model or vehicle type" className="rounded-xl border p-3"/><input value={component} onChange={event=>setComponent(event.target.value)} placeholder="Component or system" className="rounded-xl border p-3"/><input value={faultCode} onChange={event=>setFaultCode(event.target.value)} placeholder="Fault code" className="rounded-xl border p-3"/></div><div className="mt-4 space-y-3">{visible.map(fix=><article key={fix.id} className="rounded-2xl border p-4"><h3 className="font-black">{fix.title}</h3><p className="text-sm text-slate-500">{fix.status} · Revision {fix.revision}</p><p className="mt-1 text-xs text-slate-500">Created {fix.createdAt||"pending"} by {fix.createdBy||"unknown"} · Updated {fix.updatedAt||"pending"} by {fix.updatedBy||"unknown"}{fix.approvedAt?` · Approved ${fix.approvedAt} by ${fix.approvedBy||"unknown"}`:""}</p><div className="mt-3 flex gap-2">{caps.manage&&<button onClick={()=>edit(fix)} className="rounded-lg border px-3 py-2 text-xs font-bold">Edit</button>}{caps.approve&&fix.status!=="APPROVED"&&<button onClick={()=>void action(fix.id,"approve")} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white">Approve</button>}{caps.manage&&fix.status!=="INACTIVE"&&<button onClick={()=>void action(fix.id,"inactivate")} className="rounded-lg bg-slate-700 px-3 py-2 text-xs font-black text-white">Mark inactive</button>}</div></article>)}</div></section>}</div></main>;
}
